# Generated by Django 4.2.23 on 2025-07-29 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Име нагрупата')),
                ('comment', models.CharField(blank=True, default='', max_length=80, verbose_name='коментар/пояснение')),
            ],
            options={
                'verbose_name': 'Група/категория',
                'verbose_name_plural': 'Групи/категории',
            },
        ),
        migrations.CreateModel(
            name='SysParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Име на параметъра')),
                ('value', models.CharField(default='', max_length=30, verbose_name='Стойност на параметъра')),
                ('comment', models.CharField(blank=True, default='', max_length=80, verbose_name='коментар/пояснение')),
            ],
            options={
                'verbose_name': 'Системен параметър',
                'verbose_name_plural': 'Системни параметри',
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Athlete Name')),
                ('bib_number', models.CharField(max_length=10, verbose_name='Bib Number')),
                ('result_time', models.DurationField(blank=True, null=True, verbose_name='Result Time')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='main.group', verbose_name='Group/Category')),
            ],
            options={
                'verbose_name': 'Състезател',
                'verbose_name_plural': 'Състезатели',
            },
        ),
    ]
