# Generated by Django 4.2.23 on 2025-07-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='bib_number',
            field=models.IntegerField(default=0, verbose_name='Стартов номер'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='main.group', verbose_name='Група/категория'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Име на състезателя'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='result_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Време'),
        ),
    ]
