# Generated by Django 4.2.23 on 2025-07-31 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_competition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SysParam',
        ),
        migrations.AlterModelOptions(
            name='athlete',
            options={'verbose_name': 'състезател', 'verbose_name_plural': 'Състезатели'},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Състезание', 'verbose_name_plural': 'Състезания'},
        ),
        migrations.AddField(
            model_name='athlete',
            name='num',
            field=models.PositiveSmallIntegerField(default=999, null=True, verbose_name='Текущ пореден номер на пристигащ състезател'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'дисквалифициран'), (1, 'регистриран'), (2, 'финиширащ'), (3, 'финиширал')], default=1, verbose_name='Статус на състезателя'),
        ),
        migrations.AddField(
            model_name='competition',
            name='next_num',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Текущ пореден номер на пристигащ състезател'),
        ),
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Текущ статус на състезанието'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Име на състезанието'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало на състезанието'),
        ),
    ]
