# Generated by Django 4.2.23 on 2025-07-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_athlete_result_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Име на състезателя'),
        ),
    ]
