# Generated by Django 4.2.23 on 2025-08-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_athlete_result_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.CharField(default='М', max_length=1, verbose_name='Създадено от'),
        ),
    ]
