# Generated by Django 4.2.23 on 2025-08-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_athletephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletephoto',
            name='uploaded_at',
        ),
    ]
